# Generated by Django 5.2 on 2025-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="name",
            new_name="password",
        ),
        migrations.AddField(
            model_name="admin",
            name="username",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
