# Generated by Django 5.2 on 2025-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_rename_name_admin_password_admin_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="username",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
