# Generated by Django 5.2 on 2025-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_rename_username_admin_name_alter_admin_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
