# Generated by Django 5.2 on 2025-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="discription",
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
